/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.3.4).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ee.ria.tara.api;

import ee.ria.tara.model.SsoModeResponse;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.Optional;

@Validated
@Api(value = "ssoMode", description = "the ssoMode API")
public interface SsoModeApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    @ApiOperation(value = "Check what mode the application is running in", nickname = "ssoMode", notes = "Returns true if application is running in GOVSSO mode and false if running in TARA mode.", response = SsoModeResponse.class, authorizations = {
        @Authorization(value = "cookieAuth")
    }, tags={ "application", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = SsoModeResponse.class) })
    @RequestMapping(value = "/ssoMode",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<SsoModeResponse> ssoMode() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{  \"ssoMode\" : true}");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
